/*++

Copyright (C) 2021 Strings developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated C++-Header file in order to allow an easy
 use of String example library

Interface version: 1.0.0

*/

#ifndef __STRINGSEXAMPLE_DYNAMICHEADER_CPPTYPES
#define __STRINGSEXAMPLE_DYNAMICHEADER_CPPTYPES

#include "strexample_types.hpp"



/*************************************************************************************************************************
 Class definition for Base
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for StringObject
**************************************************************************************************************************/

/**
* Return incapsulated object
*
* @param[in] pStringObject - StringObject instance.
* @param[in] nNameBufferSize - size of the buffer (including trailing 0)
* @param[out] pNameNeededChars - will be filled with the count of the written bytes, or needed buffer size.
* @param[out] pNameBuffer -  buffer of Pass some strong to trigger cached parameters name., may be NULL
* @param[out] pResult - Fails in compilation
* @return error code or 0 (success)
*/
typedef StringsExampleResult (*PStringsExampleStringObject_GetMyStringObjectPtr) (StringsExample_StringObject pStringObject, const StringsExample_uint32 nNameBufferSize, StringsExample_uint32* pNameNeededChars, char * pNameBuffer, StringsExample_StringObject * pResult);

/*************************************************************************************************************************
 Global functions
**************************************************************************************************************************/

/**
* retrieves the binary version of this library.
*
* @param[out] pMajor - returns the major version of this library
* @param[out] pMinor - returns the minor version of this library
* @param[out] pMicro - returns the micro version of this library
* @return error code or 0 (success)
*/
typedef StringsExampleResult (*PStringsExampleGetVersionPtr) (StringsExample_uint32 * pMajor, StringsExample_uint32 * pMinor, StringsExample_uint32 * pMicro);

/**
* Returns the last error recorded on this object
*
* @param[in] pInstance - Instance Handle
* @param[in] nErrorMessageBufferSize - size of the buffer (including trailing 0)
* @param[out] pErrorMessageNeededChars - will be filled with the count of the written bytes, or needed buffer size.
* @param[out] pErrorMessageBuffer -  buffer of Message of the last error, may be NULL
* @param[out] pHasError - Is there a last error to query
* @return error code or 0 (success)
*/
typedef StringsExampleResult (*PStringsExampleGetLastErrorPtr) (StringsExample_Base pInstance, const StringsExample_uint32 nErrorMessageBufferSize, StringsExample_uint32* pErrorMessageNeededChars, char * pErrorMessageBuffer, bool * pHasError);

/**
* Releases shared ownership of an Instance
*
* @param[in] pInstance - Instance Handle
* @return error code or 0 (success)
*/
typedef StringsExampleResult (*PStringsExampleReleaseInstancePtr) (StringsExample_Base pInstance);

/**
* Acquires shared ownership of an Instance
*
* @param[in] pInstance - Instance Handle
* @return error code or 0 (success)
*/
typedef StringsExampleResult (*PStringsExampleAcquireInstancePtr) (StringsExample_Base pInstance);

/**
* Creates a new Variable instance
*
* @param[out] pInstance - New Variable instance
* @return error code or 0 (success)
*/
typedef StringsExampleResult (*PStringsExampleCreateStringObjectPtr) (StringsExample_StringObject * pInstance);

/*************************************************************************************************************************
 Function Table Structure
**************************************************************************************************************************/

typedef struct {
	void * m_LibraryHandle;
	PStringsExampleStringObject_GetMyStringObjectPtr m_StringObject_GetMyStringObject;
	PStringsExampleGetVersionPtr m_GetVersion;
	PStringsExampleGetLastErrorPtr m_GetLastError;
	PStringsExampleReleaseInstancePtr m_ReleaseInstance;
	PStringsExampleAcquireInstancePtr m_AcquireInstance;
	PStringsExampleCreateStringObjectPtr m_CreateStringObject;
} sStringsExampleDynamicWrapperTable;

#endif // __STRINGSEXAMPLE_DYNAMICHEADER_CPPTYPES

