/*++

Copyright (C) 2021 Strings developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated C++ Header file with the basic internal
 exception type in order to allow an easy use of String example library

Interface version: 1.0.0

*/

#ifndef __STRINGSEXAMPLE_INTERFACEEXCEPTION_HEADER
#define __STRINGSEXAMPLE_INTERFACEEXCEPTION_HEADER

#include <exception>
#include <stdexcept>
#include "strexample_types.hpp"

/*************************************************************************************************************************
 Class EStringsExampleInterfaceException
**************************************************************************************************************************/


class EStringsExampleInterfaceException : public std::exception {
protected:
	/**
	* Error code for the Exception.
	*/
	StringsExampleResult m_errorCode;
	/**
	* Error message for the Exception.
	*/
	std::string m_errorMessage;

public:
	/**
	* Exception Constructor.
	*/
	EStringsExampleInterfaceException(StringsExampleResult errorCode);

	/**
	* Custom Exception Constructor.
	*/
	EStringsExampleInterfaceException(StringsExampleResult errorCode, std::string errorMessage);

	/**
	* Returns error code
	*/
	StringsExampleResult getErrorCode();
	/**
	* Returns error message
	*/
	const char* what() const noexcept override;
};

#endif // __STRINGSEXAMPLE_INTERFACEEXCEPTION_HEADER
