/*++

Copyright (C) 2021 Strings developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated C++-Header file in order to allow an easy
 use of String example library

Interface version: 1.0.0

*/

#ifndef __STRINGSEXAMPLE_HEADER_CPP
#define __STRINGSEXAMPLE_HEADER_CPP

#ifdef __STRINGSEXAMPLE_EXPORTS
#ifdef _WIN32
#define STRINGSEXAMPLE_DECLSPEC __declspec (dllexport)
#else // _WIN32
#define STRINGSEXAMPLE_DECLSPEC __attribute__((visibility("default")))
#endif // _WIN32
#else // __STRINGSEXAMPLE_EXPORTS
#define STRINGSEXAMPLE_DECLSPEC
#endif // __STRINGSEXAMPLE_EXPORTS

#include "strexample_types.hpp"


#ifdef __cplusplus
extern "C" {
#endif

/*************************************************************************************************************************
 Class definition for Base
**************************************************************************************************************************/

/*************************************************************************************************************************
 Class definition for StringObject
**************************************************************************************************************************/

/**
* Return incapsulated object
*
* @param[in] pStringObject - StringObject instance.
* @param[in] nNameBufferSize - size of the buffer (including trailing 0)
* @param[out] pNameNeededChars - will be filled with the count of the written bytes, or needed buffer size.
* @param[out] pNameBuffer -  buffer of Pass some strong to trigger cached parameters name., may be NULL
* @param[out] pResult - Fails in compilation
* @return error code or 0 (success)
*/
STRINGSEXAMPLE_DECLSPEC StringsExampleResult stringsexample_stringobject_getmystringobject(StringsExample_StringObject pStringObject, const StringsExample_uint32 nNameBufferSize, StringsExample_uint32* pNameNeededChars, char * pNameBuffer, StringsExample_StringObject * pResult);

/*************************************************************************************************************************
 Global functions
**************************************************************************************************************************/

/**
* retrieves the binary version of this library.
*
* @param[out] pMajor - returns the major version of this library
* @param[out] pMinor - returns the minor version of this library
* @param[out] pMicro - returns the micro version of this library
* @return error code or 0 (success)
*/
STRINGSEXAMPLE_DECLSPEC StringsExampleResult stringsexample_getversion(StringsExample_uint32 * pMajor, StringsExample_uint32 * pMinor, StringsExample_uint32 * pMicro);

/**
* Returns the last error recorded on this object
*
* @param[in] pInstance - Instance Handle
* @param[in] nErrorMessageBufferSize - size of the buffer (including trailing 0)
* @param[out] pErrorMessageNeededChars - will be filled with the count of the written bytes, or needed buffer size.
* @param[out] pErrorMessageBuffer -  buffer of Message of the last error, may be NULL
* @param[out] pHasError - Is there a last error to query
* @return error code or 0 (success)
*/
STRINGSEXAMPLE_DECLSPEC StringsExampleResult stringsexample_getlasterror(StringsExample_Base pInstance, const StringsExample_uint32 nErrorMessageBufferSize, StringsExample_uint32* pErrorMessageNeededChars, char * pErrorMessageBuffer, bool * pHasError);

/**
* Releases shared ownership of an Instance
*
* @param[in] pInstance - Instance Handle
* @return error code or 0 (success)
*/
STRINGSEXAMPLE_DECLSPEC StringsExampleResult stringsexample_releaseinstance(StringsExample_Base pInstance);

/**
* Acquires shared ownership of an Instance
*
* @param[in] pInstance - Instance Handle
* @return error code or 0 (success)
*/
STRINGSEXAMPLE_DECLSPEC StringsExampleResult stringsexample_acquireinstance(StringsExample_Base pInstance);

/**
* Creates a new Variable instance
*
* @param[out] pInstance - New Variable instance
* @return error code or 0 (success)
*/
STRINGSEXAMPLE_DECLSPEC StringsExampleResult stringsexample_createstringobject(StringsExample_StringObject * pInstance);

#ifdef __cplusplus
}
#endif

#endif // __STRINGSEXAMPLE_HEADER_CPP

