/*++

Copyright (C) 2021 Strings developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated C++ Implementation file with the basic internal
 exception type in order to allow an easy use of String example library

Interface version: 1.0.0

*/


#include <string>

#include "strexample_interfaceexception.hpp"

/*************************************************************************************************************************
 Class EStringsExampleInterfaceException
**************************************************************************************************************************/
EStringsExampleInterfaceException::EStringsExampleInterfaceException(StringsExampleResult errorCode)
	: m_errorMessage(STRINGSEXAMPLE_GETERRORSTRING (errorCode))
{
	m_errorCode = errorCode;
}

EStringsExampleInterfaceException::EStringsExampleInterfaceException(StringsExampleResult errorCode, std::string errorMessage)
	: m_errorMessage(errorMessage + " (" + std::to_string (errorCode) + ")")
{
	m_errorCode = errorCode;
}

StringsExampleResult EStringsExampleInterfaceException::getErrorCode ()
{
	return m_errorCode;
}

const char * EStringsExampleInterfaceException::what () const noexcept
{
	return m_errorMessage.c_str();
}

