/*++

Copyright (C) 2021 Strings developers

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.7.0-develop.

Abstract: This is an autogenerated C++ implementation file in order to allow easy
development of String example library. It needs to be generated only once.

Interface version: 1.0.0

*/

#include "strexample_abi.hpp"
#include "strexample_interfaces.hpp"
#include "strexample_interfaceexception.hpp"

using namespace StringsExample;
using namespace StringsExample::Impl;

void CWrapper::GetVersion(StringsExample_uint32 & nMajor, StringsExample_uint32 & nMinor, StringsExample_uint32 & nMicro)
{
	nMajor = STRINGSEXAMPLE_VERSION_MAJOR;
	nMinor = STRINGSEXAMPLE_VERSION_MINOR;
	nMicro = STRINGSEXAMPLE_VERSION_MICRO;
}

bool CWrapper::GetLastError(IBase* pInstance, std::string & sErrorMessage)
{
	if (pInstance) {
		return pInstance->GetLastErrorMessage (sErrorMessage);
	} else {
		return false;
	}
}

void CWrapper::ReleaseInstance(IBase* pInstance)
{
	IBase::ReleaseBaseClassInterface(pInstance);
}

void CWrapper::AcquireInstance(IBase* pInstance)
{
	IBase::AcquireBaseClassInterface(pInstance);
}

IStringObject * CWrapper::CreateStringObject()
{
	throw EStringsExampleInterfaceException(STRINGSEXAMPLE_ERROR_NOTIMPLEMENTED);
}


